import { Inter } from 'next/font/google'
import './globals.css'
import { Apollowrapper } from '@/lib/apollo-wrapper'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Apollowrapper>
          {children}
        </Apollowrapper>
      </body>
    </html>
  )
}
